name: Debug builds
on: [push]
jobs:
  aarch64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y p7zip-full

      - name: Build
        run: ARCH=aarch64 DEBUG=true deno run --env-file -A ./ci/build.ts

      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu.AppImage
          path: build/monero-tui-aarch64-unknown-linux-gnu.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu
          path: build/monero-tui-aarch64-unknown-linux-gnu.zip
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-apple-darwin
          path: build/monero-tui-aarch64-apple-darwin.zip

  x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y p7zip-full

      - name: Build
        run: ARCH=x86_64 DEBUG=true deno run --env-file -A ./ci/build.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: build/monero-tui-x86_64-unknown-linux-gnu.zip
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu.AppImage
          path: build/monero-tui-x86_64-unknown-linux-gnu.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-apple-darwin
          path: build/monero-tui-x86_64-apple-darwin.zip
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-pc-windows-msvc
          path: build/monero-tui-x86_64-pc-windows-msvc.zip
