name: build test
on: [push]
jobs:
  build-test:
    strategy:
      fail-fast: true
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf unzip python-is-python3 p7zip-full qemu qemu-user-static
      - name: Lol
        run: |
          docker buildx ls
          DEBUG=true deno run --env-file -A build.ts
