name: Release builds
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
jobs:
  aarch64:
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Setup git credentials
        run: |
          git config --global user.email "franik.mateusz@gmail.com"
          git config --global user.name "Im-Beast"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf unzip python-is-python3 p7zip-full

      - name: Ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: env-${{ github.job }}-${{ hashFiles('.env') }}
      - name: Cache monero_c build
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.coin }}/contrib/depends/built/*
          key: env-${{ github.job }}-${{ hashFiles('.env') }}

      - name: Build
        run: |
          sudo bash -c 'echo -n -e "#!/bin/sh\necho 1" > $(which nproc)'
          sudo chmod +x $(which nproc)
          ARCH=aarch64 deno run --env-file -A ./ci/build.ts

      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu.AppImage
          path: build/monero-tui-aarch64-unknown-linux-gnu.AppImage
      - uses: actions/upload-artifact@v4
        with:
          name: aarch64-unknown-linux-gnu
          path: build/monero-tui-aarch64-unknown-linux-gnu.zip

      - name: Create release ${{ github.event.release.tag_name }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/monero-tui-aarch64-unknown-linux-gnu.zip
            build/monero-tui-aarch64-unknown-linux-gnu.AppImage
  
  x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Setup git credentials
        run: |
          git config --global user.email "franik.mateusz@gmail.com"
          git config --global user.name "Im-Beast"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config autoconf libtool ccache make cmake gcc g++ git curl lbzip2 libtinfo5 gperf unzip python-is-python3 p7zip-full

      - name: Ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: env-${{ github.job }}-${{ hashFiles('.env') }}
      - name: Cached monero_c
        uses: actions/cache@v4
        with:
          path: |
            ${{ matrix.coin }}/contrib/depends/built/*
          key: env-${{ github.job }}-${{ hashFiles('.env') }}

      - name: Build
        run: ARCH=x86_64 deno run --env-file -A ./ci/build.ts

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu
          path: build/monero-tui-x86_64-unknown-linux-gnu.zip
      - uses: actions/upload-artifact@v4
        with:
          name: x86_64-unknown-linux-gnu.AppImage
          path: build/monero-tui-x86_64-unknown-linux-gnu.AppImage

      - name: Create release ${{ github.event.release.tag_name }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/monero-tui-x86_64-unknown-linux-gnu.zip
            build/monero-tui-x86_64-unknown-linux-gnu.AppImage